servicesdocker ps -docker ps -aa:
  bpa_kalman_filter:
    image: bpa-artifact
    container_name: bpa-kalman-filter
    command: ["--benchmark", "kalman_filter"]
    volumes:
      - ./results:/app/bpa/results

  bpa_batch_bertlike:
    image: bpa-artifact
    container_name: bpa-batch-bertlike
    command: ["--benchmark", "batch_bertlike"]
    volumes:
      - ./results:/app/bpa/results

  bpa_chain100:
    image: bpa-artifact
    container_name: bpa-chain
    command: ["--benchmark", "chain100"]
    volumes:
      - ./results:/app/bpa/results

  bpa_sparse_attention:
    image: bpa-artifact
    container_name: bpa-sparse-attention
    command: ["--benchmark", "sparse_attention"]
    volumes:
      - ./results:/app/bpa/results

  bpa_comptime:
    image: bpa-artifact
    container_name: bpa-comptime
    command: ["--benchmark", "comptime"]
    volumes:
      - ./results:/app/bpa/results

  # bpa-figures:
  #   image: bpa-artifact
  #   container_name: bpa-figure-generator
  #   command: ["python3", "benchmarking/scripts/aggregate.py"]
  #   depends_on:
  #     bpa_kalman_filter:
  #       condition: service_completed_successfully
  #     bpa_batch_bertlike:
  #       condition: service_completed_successfully
  #     bpa_chain100:
  #       condition: service_completed_successfully
  #     bpa_sparse_attention:
  #       condition: service_completed_successfully
  #     bpa_comptime:
  #       condition: service_completed_successfully
  #   volumes:
  #     - ./results:/app/bpa/results
