name: CI

on:
  pull_request:
  push:
    branches: [**]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/andradekaio/mlir-base:104e82b

    steps:
      - uses: actions/checkout@v4

      - name: Configure ASP
        run: |
          cmake -S . -B build \
            -G Ninja \
            -DLLVM_DIR=$LLVM_DIR \
            -DMLIR_DIR=$MLIR_DIR

      # Build
      - name: Build ASP
        run: ninja -C build

      # Run tests
      - name: Run Tests
        run: ninja -C build check-asp
