name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    container:
      image: ghcr.io/andradekaio/mlir-base:104e82b

    steps:
      - uses: actions/checkout@v4

      - name: Configure ASP
        run: |
          cmake -S . -B build \
            -G Ninja \
            -DLLVM_DIR=$LLVM_DIR \
            -DMLIR_DIR=$MLIR_DIR

      - name: Build ASP
        run: ninja -C build

      - name: Run Tests
        env:
          LIT_OPTS: "-v -j1"
        run: ninja -C build check-bpa
